# Generated by Django 5.1.6 on 2025-02-28 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooksCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_category_name', models.CharField(max_length=50)),
                ('book_category_coverpage', models.ImageField(upload_to='Categories_Cover_Pages/')),
                ('book_category_description', models.TextField(default='No Discription Available')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=50)),
                ('book_author', models.CharField(max_length=50)),
                ('book_coverpage', models.ImageField(upload_to='BooksCoverPage/')),
                ('book_summary', models.TextField()),
                ('book_pdf', models.FileField(blank=True, null=True, upload_to='BooksPdfFiles/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.bookscategories')),
            ],
        ),
    ]
