# Generated by Django 5.1.6 on 2025-03-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
